package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTrader;
import org.linlinjava.litemall.db.domain.LitemallTraderExample;

public interface LitemallTraderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    long countByExample(LitemallTraderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTraderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    int insert(LitemallTrader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTrader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    LitemallTrader selectOneByExample(LitemallTraderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    LitemallTrader selectOneByExampleSelective(@Param("example") LitemallTraderExample example, @Param("selective") LitemallTrader.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    List<LitemallTrader> selectByExampleSelective(@Param("example") LitemallTraderExample example, @Param("selective") LitemallTrader.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    List<LitemallTrader> selectByExample(LitemallTraderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    LitemallTrader selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTrader.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    LitemallTrader selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    LitemallTrader selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTrader record, @Param("example") LitemallTraderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTrader record, @Param("example") LitemallTraderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTrader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTrader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallTraderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trader
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}