package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallOrderGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_order_goods
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_order_goods
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.goods_sn
     *
     * @mbg.generated
     */
    private String goodsSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.number
     *
     * @mbg.generated
     */
    private Short number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.specifications
     *
     * @mbg.generated
     */
    private String[] specifications;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.comment
     *
     * @mbg.generated
     */
    private Integer comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.lot
     *
     * @mbg.generated
     */
    private String lot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.serial
     *
     * @mbg.generated
     */
    private String serial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.pd_date
     *
     * @mbg.generated
     */
    private LocalDateTime pdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.exp_date
     *
     * @mbg.generated
     */
    private LocalDateTime expDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.bound_serial
     *
     * @mbg.generated
     */
    private String boundSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.max_clients_count
     *
     * @mbg.generated
     */
    private Short maxClientsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.max_register_users_count
     *
     * @mbg.generated
     */
    private Short maxRegisterUsersCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_order_goods.has_register_user_ids
     *
     * @mbg.generated
     */
    private Integer[] hasRegisterUserIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.id
     *
     * @return the value of litemall_order_goods.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.id
     *
     * @param id the value for litemall_order_goods.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.order_id
     *
     * @return the value of litemall_order_goods.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.order_id
     *
     * @param orderId the value for litemall_order_goods.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.goods_id
     *
     * @return the value of litemall_order_goods.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.goods_id
     *
     * @param goodsId the value for litemall_order_goods.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.goods_name
     *
     * @return the value of litemall_order_goods.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.goods_name
     *
     * @param goodsName the value for litemall_order_goods.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.goods_sn
     *
     * @return the value of litemall_order_goods.goods_sn
     *
     * @mbg.generated
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.goods_sn
     *
     * @param goodsSn the value for litemall_order_goods.goods_sn
     *
     * @mbg.generated
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.product_id
     *
     * @return the value of litemall_order_goods.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.product_id
     *
     * @param productId the value for litemall_order_goods.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.number
     *
     * @return the value of litemall_order_goods.number
     *
     * @mbg.generated
     */
    public Short getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.number
     *
     * @param number the value for litemall_order_goods.number
     *
     * @mbg.generated
     */
    public void setNumber(Short number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.price
     *
     * @return the value of litemall_order_goods.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.price
     *
     * @param price the value for litemall_order_goods.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.specifications
     *
     * @return the value of litemall_order_goods.specifications
     *
     * @mbg.generated
     */
    public String[] getSpecifications() {
        return specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.specifications
     *
     * @param specifications the value for litemall_order_goods.specifications
     *
     * @mbg.generated
     */
    public void setSpecifications(String[] specifications) {
        this.specifications = specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.pic_url
     *
     * @return the value of litemall_order_goods.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.pic_url
     *
     * @param picUrl the value for litemall_order_goods.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.comment
     *
     * @return the value of litemall_order_goods.comment
     *
     * @mbg.generated
     */
    public Integer getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.comment
     *
     * @param comment the value for litemall_order_goods.comment
     *
     * @mbg.generated
     */
    public void setComment(Integer comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.add_time
     *
     * @return the value of litemall_order_goods.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.add_time
     *
     * @param addTime the value for litemall_order_goods.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.update_time
     *
     * @return the value of litemall_order_goods.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.update_time
     *
     * @param updateTime the value for litemall_order_goods.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.deleted
     *
     * @return the value of litemall_order_goods.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.deleted
     *
     * @param deleted the value for litemall_order_goods.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.lot
     *
     * @return the value of litemall_order_goods.lot
     *
     * @mbg.generated
     */
    public String getLot() {
        return lot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.lot
     *
     * @param lot the value for litemall_order_goods.lot
     *
     * @mbg.generated
     */
    public void setLot(String lot) {
        this.lot = lot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.serial
     *
     * @return the value of litemall_order_goods.serial
     *
     * @mbg.generated
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.serial
     *
     * @param serial the value for litemall_order_goods.serial
     *
     * @mbg.generated
     */
    public void setSerial(String serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.pd_date
     *
     * @return the value of litemall_order_goods.pd_date
     *
     * @mbg.generated
     */
    public LocalDateTime getPdDate() {
        return pdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.pd_date
     *
     * @param pdDate the value for litemall_order_goods.pd_date
     *
     * @mbg.generated
     */
    public void setPdDate(LocalDateTime pdDate) {
        this.pdDate = pdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.exp_date
     *
     * @return the value of litemall_order_goods.exp_date
     *
     * @mbg.generated
     */
    public LocalDateTime getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.exp_date
     *
     * @param expDate the value for litemall_order_goods.exp_date
     *
     * @mbg.generated
     */
    public void setExpDate(LocalDateTime expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.bound_serial
     *
     * @return the value of litemall_order_goods.bound_serial
     *
     * @mbg.generated
     */
    public String getBoundSerial() {
        return boundSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.bound_serial
     *
     * @param boundSerial the value for litemall_order_goods.bound_serial
     *
     * @mbg.generated
     */
    public void setBoundSerial(String boundSerial) {
        this.boundSerial = boundSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.max_clients_count
     *
     * @return the value of litemall_order_goods.max_clients_count
     *
     * @mbg.generated
     */
    public Short getMaxClientsCount() {
        return maxClientsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.max_clients_count
     *
     * @param maxClientsCount the value for litemall_order_goods.max_clients_count
     *
     * @mbg.generated
     */
    public void setMaxClientsCount(Short maxClientsCount) {
        this.maxClientsCount = maxClientsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_order_goods.max_register_users_count
     *
     * @return the value of litemall_order_goods.max_register_users_count
     *
     * @mbg.generated
     */
    public Short getMaxRegisterUsersCount() {
        return maxRegisterUsersCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_order_goods.max_register_users_count
     *
     * @param maxRegisterUsersCount the value for litemall_order_goods.max_register_users_count
     *
     * @mbg.generated
     */
    public void setMaxRegisterUsersCount(Short maxRegisterUsersCount) {
        this.maxRegisterUsersCount = maxRegisterUsersCount;
    }

/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_user.trader_ids
     *
     * @return the value of litemall_user.trader_ids
     *
     * @mbg.generated
     */
    public Integer[] getHasRegisterUserIds() {
        return hasRegisterUserIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_user.trader_ids
     *
     * @param hasRegisterUserIds the value for litemall_user.trader_ids
     *
     * @mbg.generated
     */
    public void setHasRegisterUserIds(Integer[] hasRegisterUserIds) {
        this.hasRegisterUserIds = hasRegisterUserIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", goodsSn=").append(goodsSn);
        sb.append(", productId=").append(productId);
        sb.append(", number=").append(number);
        sb.append(", price=").append(price);
        sb.append(", specifications=").append(specifications);
        sb.append(", picUrl=").append(picUrl);
        sb.append(", comment=").append(comment);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", lot=").append(lot);
        sb.append(", serial=").append(serial);
        sb.append(", pdDate=").append(pdDate);
        sb.append(", expDate=").append(expDate);
        sb.append(", boundSerial=").append(boundSerial);
        sb.append(", maxClientsCount=").append(maxClientsCount);
        sb.append(", maxRegisterUsersCount=").append(maxRegisterUsersCount);
        sb.append(", hasRegisterUserIds=").append(hasRegisterUserIds);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallOrderGoods other = (LitemallOrderGoods) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getGoodsName() == null ? other.getGoodsName() == null : this.getGoodsName().equals(other.getGoodsName()))
            && (this.getGoodsSn() == null ? other.getGoodsSn() == null : this.getGoodsSn().equals(other.getGoodsSn()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (Arrays.equals(this.getSpecifications(), other.getSpecifications()))
            && (this.getPicUrl() == null ? other.getPicUrl() == null : this.getPicUrl().equals(other.getPicUrl()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getLot() == null ? other.getLot() == null : this.getLot().equals(other.getLot()))
            && (this.getSerial() == null ? other.getSerial() == null : this.getSerial().equals(other.getSerial()))
            && (this.getPdDate() == null ? other.getPdDate() == null : this.getPdDate().equals(other.getPdDate()))
            && (this.getExpDate() == null ? other.getExpDate() == null : this.getExpDate().equals(other.getExpDate()))
            && (this.getBoundSerial() == null ? other.getBoundSerial() == null : this.getBoundSerial().equals(other.getBoundSerial()))
            && (this.getMaxClientsCount() == null ? other.getMaxClientsCount() == null : this.getMaxClientsCount().equals(other.getMaxClientsCount()))
            && (this.getMaxRegisterUsersCount() == null ? other.getMaxRegisterUsersCount() == null : this.getMaxRegisterUsersCount().equals(other.getMaxRegisterUsersCount()))
            && (this.getHasRegisterUserIds() == null ? other.getHasRegisterUserIds() == null : this.getHasRegisterUserIds().equals(other.getHasRegisterUserIds()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_goods
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getGoodsName() == null) ? 0 : getGoodsName().hashCode());
        result = prime * result + ((getGoodsSn() == null) ? 0 : getGoodsSn().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + (Arrays.hashCode(getSpecifications()));
        result = prime * result + ((getPicUrl() == null) ? 0 : getPicUrl().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getLot() == null) ? 0 : getLot().hashCode());
        result = prime * result + ((getSerial() == null) ? 0 : getSerial().hashCode());
        result = prime * result + ((getPdDate() == null) ? 0 : getPdDate().hashCode());
        result = prime * result + ((getExpDate() == null) ? 0 : getExpDate().hashCode());
        result = prime * result + ((getBoundSerial() == null) ? 0 : getBoundSerial().hashCode());
        result = prime * result + ((getMaxClientsCount() == null) ? 0 : getMaxClientsCount().hashCode());
        result = prime * result + ((getMaxRegisterUsersCount() == null) ? 0 : getMaxRegisterUsersCount().hashCode());
        result = prime * result + ((getHasRegisterUserIds() == null) ? 0 : getHasRegisterUserIds().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_order_goods
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_order_goods
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        orderId("order_id", "orderId", "INTEGER", false),
        goodsId("goods_id", "goodsId", "INTEGER", false),
        goodsName("goods_name", "goodsName", "VARCHAR", false),
        goodsSn("goods_sn", "goodsSn", "VARCHAR", false),
        productId("product_id", "productId", "INTEGER", false),
        number("number", "number", "SMALLINT", true),
        price("price", "price", "DECIMAL", false),
        specifications("specifications", "specifications", "VARCHAR", false),
        picUrl("pic_url", "picUrl", "VARCHAR", false),
        comment("comment", "comment", "INTEGER", true),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false),
        lot("lot", "lot", "VARCHAR", false),
        serial("serial", "serial", "VARCHAR", false),
        pdDate("pd_date", "pdDate", "TIMESTAMP", false),
        expDate("exp_date", "expDate", "TIMESTAMP", false),
        boundSerial("bound_serial", "boundSerial", "VARCHAR", false),
        maxClientsCount("max_clients_count", "maxClientsCount", "SMALLINT", false),
        maxRegisterUsersCount("max_register_users_count", "maxRegisterUsersCount", "SMALLINT", false),
        hasRegisterUserIds("has_register_user_ids", "hasRegisterUserIds", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_order_goods
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}