web:
  upload-path: '/Users/flashcloudf/dev/mobile_dev/worksapce/sungole-icloud/grsoft/litemall/storage'
  default-avatar-url: 'https://sungole-icloud.oss-cn-shenzhen.aliyuncs.com/litemall/default-avatar.jpg'  #TODO: change to your own default avatar URL
  default-avatar-local: '/Users/flashcloudf/dev/mobile_dev/worksapce/sungole-icloud/grsoft/litemall/storage/images/avatar/avatar.jpg' 

spring:
  profiles:
    active: db, core, wx
  messages:
    encoding: UTF-8
  resources:
    static-locations: classpath:/static/, file:${web.upload-path}

server:
  port: 8082

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.wx:  DEBUG
    org.linlinjava.litemall:  ERROR

swagger:
  production: false